/* ISC license. */

/* Generated by: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir='${prefix}/include' --mandir='${prefix}/share/man' --infodir='${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir='${prefix}/lib/x86_64-linux-gnu' --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --dynlibdir='${prefix}/lib/x86_64-linux-gnu' --bindir='${prefix}/bin' --libexecdir='${prefix}/libexec' --libdir='${prefix}/lib/x86_64-linux-gnu' --includedir='${prefix}/include' --livedir=/run/s6-rc --with-sysdeps='${prefix}/lib/x86_64-linux-gnu/skalibs/sysdeps' --includedir='${prefix}/include' --with-lib='${prefix}/lib/skalibs' --with-lib='${prefix}/lib/execline' --with-lib='${prefix}/lib/s6' --enable-shared --enable-absolute-paths */

#ifndef S6RC_CONFIG_H
#define S6RC_CONFIG_H

#define S6RC_VERSION "0.5.6.0"
#define S6RC_BINPREFIX "/usr/bin/"
#define S6RC_EXTBINPREFIX "/usr/bin/"
#define S6RC_EXTLIBEXECPREFIX "/usr/libexec/"
#define S6RC_LIBEXECPREFIX "/usr/libexec/"
#define S6RC_SYSCONFPREFIX "/etc/"
#define S6RC_LIVE_BASE "/run/s6-rc"

#endif
