# Option to actually spawn the getty when the service starts. Set to "yes" to enable.
SPAWN="yes"

# Arguments to pass to getty.
ARGS="-L -8 tty10 115200"

# Getty program to use.
GETTY="/sbin/agetty"
