/* ISC license. */

/* Generated by: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir='${prefix}/include' --mandir='${prefix}/share/man' --infodir='${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir='${prefix}/lib/x86_64-linux-gnu' --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --exec-prefix='${prefix}' --dynlibdir='${prefix}/lib/x86_64-linux-gnu' --bindir='${prefix}/bin' --libexecdir='${prefix}/libexec' --libdir='${prefix}/lib/x86_64-linux-gnu' --includedir='${prefix}/include' --tmpfsdir=/run --with-sysdeps='${prefix}/lib/x86_64-linux-gnu/skalibs/sysdeps' --with-lib='${prefix}/lib/skalibs' --with-lib='${prefix}/lib/execline' --with-lib='${prefix}/lib/s6' --enable-shared --enable-absolute-paths */

#ifndef S6_LINUX_INIT_CONFIG_H
#define S6_LINUX_INIT_CONFIG_H

#define S6_LINUX_INIT_VERSION "1.1.3.0"
#define S6_LINUX_INIT_BINPREFIX "/usr/bin/"
#define S6_LINUX_INIT_EXTBINPREFIX "/usr/bin/"
#define S6_LINUX_INIT_EXTLIBEXECPREFIX "/usr/libexec/"
#define S6_LINUX_INIT_LIBEXECPREFIX "/usr/libexec/"
#define S6_LINUX_INIT_SYSCONFPREFIX "/etc/"
#define S6_LINUX_INIT_SKELDIR "/usr/etc/s6-linux-init/skel"
#define S6_LINUX_INIT_TMPFS "/run"
#define S6_LINUX_INIT_SCANDIR "service"

#undef S6_LINUX_INIT_UTMPD_PATH
#undef S6_LINUX_INIT_WTMPD_PATH

#endif
