#!/bin/sh -euC

# Disable service, if /dev/tty{N} does not exist. See #914788.
if ! test -c /dev/tty6 ; then
	mv /etc/service/getty-tty6 /etc/service/.getty-tty6
	exit 0
fi

fuser -v /dev/tty6 && exit 163

! type fgetty >/dev/null 2>&1 || exec chpst -P fgetty tty6
exec chpst -P getty 38400 tty6 linux
