#!/bin/sh -euC

# Disable service, if /dev/tty{N} does not exist. See #914788.
if ! test -c /dev/tty4 ; then
	mv /etc/service/getty-tty4 /etc/service/.getty-tty4
	exit 0
fi

fuser -v /dev/tty4 && exit 163

! type fgetty >/dev/null 2>&1 || exec chpst -P fgetty tty4
exec chpst -P getty 38400 tty4 linux
