/* ISC license. */

/* Generated by: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir='${prefix}/include' --mandir='${prefix}/share/man' --infodir='${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir='${prefix}/lib/x86_64-linux-gnu' --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --dynlibdir='${prefix}/lib/x86_64-linux-gnu' --libdir='${prefix}/lib/x86_64-linux-gnu' --includedir='${prefix}/include/x86_64-linux-gnu' --libexecdir='${prefix}/lib/x86_64-linux-gnu/s6' --with-sysdeps=/usr/lib/x86_64-linux-gnu/skalibs/sysdeps --enable-absolute-paths --enable-shared --disable-allstatic */

#ifndef S6_CONFIG_H
#define S6_CONFIG_H

#define S6_VERSION "2.13.2.0"
#define S6_BINPREFIX "/usr/bin/"
#define S6_EXTBINPREFIX "/usr/bin/"
#define S6_EXTLIBEXECPREFIX "/usr/lib/x86_64-linux-gnu/s6/"
#define S6_LIBEXECPREFIX "/usr/lib/x86_64-linux-gnu/s6/"
#define S6_SYSCONFPREFIX "/etc/"
#undef S6_USE_EXECLINE
#define S6_USE_EXECLINE

#endif
