Welcome to antiX!

To start the system, type one of the label names below and press [enter]:

           live   antiX-26 x64-core (28 January 2026)
          runit   antiX-26 x64-core (runit)
       sysVinit   antiX-26 x64-core (sysvinit)
          dinit   antiX-26 x64-core (dinit)
          s6-rc   antiX-26 x64-core (s6-rc)
          s6-66   antiX-26 x64-core (s6-66)
           safe   Safe Video Mode
       failsafe   Failsafe Boot
       harddisk   Boot from Hard Disk
        memtest   Memory Test
           grub   Switch to Grub Bootloader
