/* ISC license. */

/* Generated by: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir='${prefix}/include' --mandir='${prefix}/share/man' --infodir='${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir='${prefix}/lib/x86_64-linux-gnu' --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --build=x86_64-linux-gnu --host=x86_64-linux-gnu --dynlibdir='${prefix}/lib/x86_64-linux-gnu' --libdir='${prefix}/lib/x86_64-linux-gnu' --includedir='${prefix}/include/x86_64-linux-gnu' --sysdepdir='${prefix}/lib/x86_64-linux-gnu/skalibs/sysdeps' */

#ifndef SKALIBS_CONFIG_H
#define SKALIBS_CONFIG_H

#define SKALIBS_VERSION "2.14.4.0"
#define SKALIBS_DEFAULTPATH "/usr/bin:/bin"
#define SKALIBS_ETC "/etc"
#define SKALIBS_SPROOT ""
#define SKALIBS_HOME ""
#undef SKALIBS_FLAG_CLOCKISTAI
#define SKALIBS_FLAG_WANTIPV6
#undef SKALIBS_FLAG_PREFERSELECT

#endif
