# config file for s6-db-reload

# default location of user services
# USERPATH="$USER_HOME/.local/share"
USERPATH="$(/usr/lib/execline/bin/homeof $(whoami))"

# default timestamp date format
# TIMESTAMP=$(date +%s%N)
TIMESTAMP=@$(date '+%Y%m%d-%H%M%S')
