/* ISC license. */

/* Generated by: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir='${prefix}/include' --mandir='${prefix}/share/man' --infodir='${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir='${prefix}/lib/x86_64-linux-gnu' --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --dynlibdir='${prefix}/lib' --libdir='${prefix}/lib' --libexecdir='${prefix}/libexec' --bindir='${prefix}/bin' --with-lib='${prefix}/lib/skalibs' --with-lib='${prefix}/lib/execline' --with-lib='${prefix}/lib/s6' --with-sysdeps='${prefix}/lib/x86_64-linux-gnu/skalibs/sysdeps' --shebangdir='${prefix}/lib/execline/bin' --with-s6-log-timestamp=iso --includedir='${prefix}/include' */

#ifndef S6_PORTABLE_UTILS_CONFIG_H
#define S6_PORTABLE_UTILS_CONFIG_H

#define S6_PORTABLE_UTILS_VERSION "2.3.1.0"
#define S6_PORTABLE_UTILS_BINPREFIX ""
#define S6_PORTABLE_UTILS_EXTBINPREFIX ""
#define S6_PORTABLE_UTILS_EXTLIBEXECPREFIX "/usr/libexec/"
#define S6_PORTABLE_UTILS_LIBEXECPREFIX "/usr/libexec/"
#define S6_PORTABLE_UTILS_SYSCONFPREFIX "/etc/"

#endif
