#!/bin/sh -euC

# Disable service, if /dev/tty{N} does not exist. See #914788.
if ! test -c /dev/tty3 ; then
	mv /etc/service/getty-tty3 /etc/service/.getty-tty3
	exit 0
fi

fuser -v /dev/tty3 && exit 163

! type fgetty >/dev/null 2>&1 || exec chpst -P fgetty tty3
exec chpst -P getty 38400 tty3 linux
