VERBOSITY=1
LIVE=/run/66
PATH=/usr/bin:/usr/sbin:/usr/libexec:/usr/lib/execline/bin:/usr/lib/execline/sbin:/usr/local/bin:/usr/local/sbin:/usr/games:/usr/local/games
TREE=boot
RCINIT=/etc/66/rc.init
RCSHUTDOWN=/etc/66/rc.shutdown
RCSHUTDOWNFINAL=/etc/66/rc.shutdown.final
UMASK=0022
RESCAN=0
CONTAINER=0
RCINIT_CONTAINER=/etc/66/rc.init.container
CATCHLOG=1
