#!/usr/bin/execlineb -S0

importas -iu VERBOSITY VERBOSITY
importas -iu TREE TREE
importas -iu LIVE LIVE

## By default the output goes to the uncaught-logs at
## /run/66/log/0/current
## If you want to see it on console uncomment the following line
#
# redirfd -w 1 /dev/console

if -n {
    if { 66-echo -- "[Start services of tree ${TREE}...]" }
    66 -v${VERBOSITY} -l ${LIVE} tree start ${TREE}
}

if { 66-echo -- "rc.init: fatal: please see the log at ${LIVE}/log/0/current" }

exit 111
